---
title: "6-Month_HumidityCorrection"
author: "Meg Fay"
date: "2023-07-06"
output: html_document
---
```{r setup, include=FALSE}
#Library
pacman::p_load(lubridate, dplyr, tidyverse, ggpubr, openair, openairmaps, ggplot2, worldmet, purrr)

#import DEM data from file
DEM_sensor<- read.csv("C:/Users/mrfay/OneDrive - University of Vermont/Desktop/BPVD/PM/data/Compiled_RIDEM_Data_6.13.23.csv")

#convert date
DEM_sensor$Date <- as_datetime(DEM_sensor$Date, format =  "%Y-%m-%d %H:%M:%S")
colnames(DEM_sensor)[1] <- "date"
#View(DEM_sensor)

# import baseline corrected sensor data
All_Sensors_Corrected <- read.csv("C:/Users/mrfay/OneDrive - University of Vermont/Desktop/BPVD/PM/data/6month_pm25_offset.csv")

# convert date
All_Sensors_Corrected$date <- as_datetime(All_Sensors_Corrected$date, format =  "%Y-%m-%d %H:%M:%S")
#View(All_Sensors_Corrected)
```

```{r take hourly averages of sensor data}
#Generate Hourly averages for pm2_5_corrected, temp, rh of SENSOR 1

MJF_hourly <-  All_Sensors_Corrected %>%
  filter(Sensor == "Myron J. Francis Elementary") %>%
  mutate(date_hourly = floor_date(date, unit = "hour"))

MJF_pm2_5_corrected_hourly <- MJF_hourly %>%
  group_by(date_hourly) %>%
  summarise_at(vars(pm2_5_corrected), list(pm2_5_corrected = mean))

MJF_rh_hourly <- MJF_hourly %>%
  group_by(date_hourly) %>%
  summarise_at(vars(rh), list(rh = mean))

#Merge into new hourly dataframe
MJF_hourly <- merge(MJF_pm2_5_corrected_hourly, MJF_rh_hourly, by = "date_hourly")
```

```{r merge datasets}
DEM_sensor$date_hourly <- DEM_sensor$date
PM_Data_Merge <- merge(DEM_sensor, MJF_hourly, by = "date_hourly")

write_csv(PM_Data_Merge, "C:/Users/mrfay/OneDrive - University of Vermont/Desktop/BPVD/PM/data/6month_pm25_mjf_dem_merge.csv")
```

```{r add seasonal variable to dataframe}
# create a month column
PM_Data_Merge$month <- month(PM_Data_Merge$date_hourly)

# create a season column
PM_Data_Merge$season <- ifelse(PM_Data_Merge$month %in% c(12, 1, 2), "Winter",
                               ifelse(PM_Data_Merge$month %in% c(3, 4, 5), "Spring",
                                      ifelse(PM_Data_Merge$month %in% c(6, 7, 8), "Summer",
                                             ifelse(PM_Data_Merge$month %in% c(9, 10, 11), "Fall", NA))))
```

```{r fitting to hygroscopic growth function}
#defining the empirical formula
hygro.eq <- function(m, k) {
   df$x*m/(1+k/((100/df$RH)-1))
}

szns <- unique(PM_Data_Merge$season)

# Create an empty dataframe to store m, k and season
fit_results <- data.frame()

for (szn in szns) {
  data <- PM_Data_Merge %>% 
    filter(season == szn)
  x <- data$pm2_5_corrected
  y <- data$PM2_5
  RH <- data$rh
  df <- data.frame(y,x,RH)
  df <- df %>% drop_na()
  fit <- nls(y ~ hygro.eq(m, k), data = df, start = list(m = 0.5, k = 1))
  fit_coefs <- coef(fit)
  m <- as.numeric(fit_coefs[1])
  k <- as.numeric(fit_coefs[2])

  # Add the results to the dataframe
  fit_results <- rbind(fit_results, data.frame(season = szn, m = m, k = k))
}
```

```{r applying empirical correction formula}

# create an hourly column in All_Sensors_Corrected
All_Sensors_Corrected <-  All_Sensors_Corrected %>%
  mutate(date_hourly = floor_date(date, unit = "hour"))

# merge with RIDEM data
sensor_fit_merge <- merge(DEM_sensor, All_Sensors_Corrected, by= "date_hourly")

# add m and k values to sensor_fit_merge based on season
# create a month column in sensor_fit_merge
sensor_fit_merge$month <- month(sensor_fit_merge$date_hourly)
# create a season column in sensor_fit_merge
sensor_fit_merge$season <- ifelse(sensor_fit_merge$month %in% c(12, 1, 2), "Winter",
                                  ifelse(sensor_fit_merge$month %in% c(3, 4, 5), "Spring",
                                         ifelse(sensor_fit_merge$month %in% c(6, 7, 8), "Summer",
                                                ifelse(sensor_fit_merge$month %in% c(9, 10, 11), "Fall", NA))))
sensor_fit_merge <- merge(sensor_fit_merge, fit_results, by = "season")

sensor_fit_merge$pm2_5_dry <- (sensor_fit_merge$pm2_5_corrected)*(sensor_fit_merge$m/(1+sensor_fit_merge$k/((100/sensor_fit_merge$rh)-1)))
#View(sensor_fit_merge)
```

```{r save output}
# subset variables
PVD_PM_Cal <- subset(sensor_fit_merge, select = c(lat, lon, date.y, date_hourly, season, m, k, Sensor, code, rh, pm2_5_corrected, pm2_5_dry, PM2_5))
colnames(PVD_PM_Cal) <- c("lat", "lon", "date", "date_hourly", "season", "m", "k", "Sensor", "code", "rh", "pm2_5_corrected", "pm2_5_dry", "PM2_5_RIDEM")
#View(PVD_PM_Cal)


#write csv with results
PVD_PM_Cal_df <- as.data.frame(PVD_PM_Cal)
PVD_PM_Cal_df$code <- sapply(PVD_PM_Cal_df$code, paste, collapse = ",")
PVD_PM_Cal_df$code <- as.character(PVD_PM_Cal_df$code)
PVD_PM_Cal_df$date <- as.POSIXct(PVD_PM_Cal_df$date)

write.csv(PVD_PM_Cal_df, "C:/Users/mrfay/OneDrive - University of Vermont/Desktop/BPVD/PM/data/6month_pm25_offset_humidity.csv")
```
